export { default as ProductCTA } from './dashboard-cta'
export { default as ProductCategory } from './dashboard-category'
export { default as DashboardHero } from './dashboard-hero'
export { default as ProductHowItWorks } from './dashboard-how-it-works'
export { default as ProductSmokingHero } from './dashboard-smoking-hero'
export { default as ProductValue } from './dashboard-value'
export { default as SDashboardSection } from './dashboard-section'
