export { default as ProductCTA } from './product-cta'
export { default as ProductCategory } from './product-category'
export { default as DashboardHero } from './dashboard-hero'
export { default as ProductHowItWorks } from './product-how-it-works'
export { default as ProductSmokingHero } from './product-smoking-hero'
export { default as ProductValue } from './product-value'
export { default as SDashboardSection } from './dashboard-section'
